sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DAnimation.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DCore.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DExtras.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DInput.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DQuick.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DLogic.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DQuickScene2D.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/Qt3DRender.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtConcurrent.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtCore.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtDBus.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtGamepad.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtGui.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtLocation.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtNetwork.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtPositioning.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtPositioningQuick.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtPrintSupport.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtQml.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtQuick.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtSerialBus.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtSerialPort.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtSql.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtTextToSpeech.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtVirtualKeyboard.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtWebChannel.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtWebEngine.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtWebEngineCore.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtWebSockets.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtWebView.framework/
sh contrib/macdeploy/patchQtFramework.sh dist/AXEL\ Wallet.app/Contents/Frameworks/QtWidgets.framework/
